
＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 00:00:13,099                                   
【线程编号】[9]                                   
【执行时间】[3067]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】378                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.IO.IOException: 文件“E:\Desktop\FDownLoad\navicatforsqlite_pcsoft.com.cn(2).zip.fd”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   在 UserComponents.DownLoadService.HttpDownLoadTask.GetInfoFromMeta() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 360                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 00:00:13,138                                   
【线程编号】[18]                                   
【执行时间】[3106]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 00:00:38,454                                   
【线程编号】[9]                                   
【执行时间】[2899]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs                                   
【出错行号】183                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NotImplementedException: 未实现该方法或操作。
   在 UserComponents.DownLoadService.HttpDownLoadTask.Fail() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 23
   在 UserComponents.DownLoadService.DownLoadService.FailTask(DownLoadTask task) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadService.cs:行号 309
   在 FlashDownLoad.DownLoadForm.FailTask(DownLoadTask task) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 568
   在 FlashDownLoad.DownLoadForm.DownLoadForm_Load(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 136                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 20:57:42,562                                   
【线程编号】[12]                                   
【执行时间】[8105]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 20:57:53,321                                   
【线程编号】[12]                                   
【执行时间】[18864]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:04:33,435                                   
【线程编号】[11]                                   
【执行时间】[32039]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:06:28,818                                   
【线程编号】[15]                                   
【执行时间】[147422]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:09:40,051                                   
【线程编号】[8]                                   
【执行时间】[11944]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:09:42,521                                   
【线程编号】[8]                                   
【执行时间】[14414]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:12:16,278                                   
【线程编号】[12]                                   
【执行时间】[113416]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】47                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.DownLoadForm.Task_TaskStart(Object sender, TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 776
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskStart(TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 589
   在 UserComponents.DownLoadService.HttpDownLoadTask.Start() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 39                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:55,152                                   
【线程编号】[20]                                   
【执行时间】[105418]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.IO.IOException: 无法从传输连接中读取数据: 你的主机中的软件中止了一个已建立的连接。。 ---> System.Net.Sockets.SocketException: 你的主机中的软件中止了一个已建立的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 150                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:55,171                                   
【线程编号】[16]                                   
【执行时间】[105437]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.IO.IOException: 无法从传输连接中读取数据: 你的主机中的软件中止了一个已建立的连接。。 ---> System.Net.Sockets.SocketException: 你的主机中的软件中止了一个已建立的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 150                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:55,231                                   
【线程编号】[15]                                   
【执行时间】[105497]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 套接字操作尝试一个无法连接的主机。 171.11.231.89:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:55,421                                   
【线程编号】[18]                                   
【执行时间】[105687]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 套接字操作尝试一个无法连接的主机。 171.11.231.89:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:57,586                                   
【线程编号】[21]                                   
【执行时间】[107852]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 未能解析此远程名称: 'd.pcsoft.com.cn'
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:57,592                                   
【线程编号】[20]                                   
【执行时间】[107858]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 未能解析此远程名称: 'd.pcsoft.com.cn'
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:57,595                                   
【线程编号】[16]                                   
【执行时间】[107861]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 未能解析此远程名称: 'd.pcsoft.com.cn'
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:57,600                                   
【线程编号】[18]                                   
【执行时间】[107866]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 未能解析此远程名称: 'd.pcsoft.com.cn'
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:57,604                                   
【线程编号】[15]                                   
【执行时间】[107870]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 未能解析此远程名称: 'd.pcsoft.com.cn'
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:17:57,609                                   
【线程编号】[22]                                   
【执行时间】[107875]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】177                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Net.WebException: 未能解析此远程名称: 'd.pcsoft.com.cn'
   在 System.Net.HttpWebRequest.GetResponse()
   在 UserComponents.DownLoadService.HttpDownLoadTask.StartOneThread(Object state) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 143                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:30:00,566                                   
【线程编号】[11]                                   
【执行时间】[7637]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】47                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.DownLoadForm.Task_TaskStart(Object sender, TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 776
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskStart(TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 589
   在 UserComponents.DownLoadService.HttpDownLoadTask.Start() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 35                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 21:41:13,505                                   
【线程编号】[11]                                   
【执行时间】[144449]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:11:17,015                                   
【线程编号】[13]                                   
【执行时间】[88520]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】47                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.DownLoadForm.Task_TaskStart(Object sender, TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 777
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskStart(TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 589
   在 UserComponents.DownLoadService.HttpDownLoadTask.Start() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 39                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:35:40,485                                   
【线程编号】[14]                                   
【执行时间】[90097]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.InvalidOperationException: 线程间操作无效: 从不是创建控件“lblStatus”的线程访问它。
   在 System.Windows.Forms.Control.get_Handle()
   在 System.Windows.Forms.Control.set_WindowText(String value)
   在 System.Windows.Forms.Control.set_Text(String value)
   在 DevExpress.XtraEditors.LabelControl.set_Text(String value)
   在 UserComponents.FlashDownLoadComp.DownLoadTaskItem.SetItemStatus() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\DownLoadTaskItem.cs:行号 107
   在 UserComponents.FlashDownLoadComp.TaskItem.set_ItemStatus(TaskStatus value) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\TaskItem.cs:行号 162
   在 FlashDownLoad.DownLoadForm.Task_TaskFinish(Object sender, TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 714
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskFinish(TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 616
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 118                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:57:03,322                                   
【线程编号】[12]                                   
【执行时间】[20848]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:57:06,333                                   
【线程编号】[12]                                   
【执行时间】[23858]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:57:11,493                                   
【线程编号】[12]                                   
【执行时间】[29018]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:19,397                                   
【线程编号】[9]                                   
【执行时间】[23988]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:22,994                                   
【线程编号】[9]                                   
【执行时间】[27586]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:25,247                                   
【线程编号】[9]                                   
【执行时间】[29838]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:42,152                                   
【线程编号】[9]                                   
【执行时间】[8294]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:53,268                                   
【线程编号】[9]                                   
【执行时间】[19411]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:54,345                                   
【线程编号】[9]                                   
【执行时间】[20487]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:54,852                                   
【线程编号】[9]                                   
【执行时间】[20994]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:55,051                                   
【线程编号】[9]                                   
【执行时间】[21193]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:58:55,266                                   
【线程编号】[9]                                   
【执行时间】[21409]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:59:01,959                                   
【线程编号】[9]                                   
【执行时间】[28101]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:59:55,967                                   
【线程编号】[9]                                   
【执行时间】[16889]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 22:59:59,477                                   
【线程编号】[9]                                   
【执行时间】[20399]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs                                   
【出错行号】80                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SQLite.SQLiteException: constraint failed
UNIQUE constraint failed: TableTask.TaskId
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction, Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(Boolean throwOnClosedConnection)
   在 System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__b()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy)
   在 System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass9.<SaveChanges>b__6()
   在 System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.NewTaskForm.btnDownLoad_Click(Object sender, EventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\NewTaskForm.cs:行号 71                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:01:17,509                                   
【线程编号】[20]                                   
【执行时间】[47164]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】47                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.DownLoadForm.Task_TaskStart(Object sender, TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 799
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskStart(TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 589
   在 UserComponents.DownLoadService.HttpDownLoadTask.Start() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 39                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:01:40,311                                   
【线程编号】[13]                                   
【执行时间】[69967]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.InvalidOperationException: 线程间操作无效: 从不是创建控件“lblStatus”的线程访问它。
   在 System.Windows.Forms.Control.get_Handle()
   在 System.Windows.Forms.Control.set_WindowText(String value)
   在 System.Windows.Forms.Control.set_Text(String value)
   在 DevExpress.XtraEditors.LabelControl.set_Text(String value)
   在 UserComponents.FlashDownLoadComp.DownLoadTaskItem.SetItemStatus() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\DownLoadTaskItem.cs:行号 107
   在 UserComponents.FlashDownLoadComp.TaskItem.set_ItemStatus(TaskStatus value) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\TaskItem.cs:行号 162
   在 FlashDownLoad.DownLoadForm.Task_TaskFinish(Object sender, TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 720
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskFinish(TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 616
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 118                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:08:11,146                                   
【线程编号】[21]                                   
【执行时间】[43391]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs                                   
【出错行号】806                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.DownLoadForm.Task_TaskStart(Object sender, TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 801                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:08:11,166                                   
【线程编号】[16]                                   
【执行时间】[43411]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:08:34,844                                   
【线程编号】[14]                                   
【执行时间】[67090]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.InvalidOperationException: 线程间操作无效: 从不是创建控件“lblStatus”的线程访问它。
   在 System.Windows.Forms.Control.get_Handle()
   在 System.Windows.Forms.Control.set_WindowText(String value)
   在 System.Windows.Forms.Control.set_Text(String value)
   在 DevExpress.XtraEditors.LabelControl.set_Text(String value)
   在 UserComponents.FlashDownLoadComp.DownLoadTaskItem.SetItemStatus() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\DownLoadTaskItem.cs:行号 107
   在 UserComponents.FlashDownLoadComp.TaskItem.set_ItemStatus(TaskStatus value) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\TaskItem.cs:行号 162
   在 FlashDownLoad.DownLoadForm.Task_TaskFinish(Object sender, TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 720
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskFinish(TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 616
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 118                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:10:36,021                                   
【线程编号】[21]                                   
【执行时间】[40601]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs                                   
【出错行号】806                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   在 System.Data.Entity.DbContext.SaveChanges()
   在 FlashDownLoad.DownLoadForm.Task_TaskStart(Object sender, TaskStartEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 801                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:10:36,036                                   
【线程编号】[21]                                   
【执行时间】[40616]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 102                                   
【错误详情】

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2018-06-27 23:16:43,396                                   
【线程编号】[11]                                   
【执行时间】[53513]毫秒                                   
【出错文件】E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs                                   
【出错行号】123                                   
【出错的类】logerror 属性[(null)]                                   
【错误描述】System.InvalidOperationException: 线程间操作无效: 从不是创建控件“lblStatus”的线程访问它。
   在 System.Windows.Forms.Control.get_Handle()
   在 System.Windows.Forms.Control.set_WindowText(String value)
   在 System.Windows.Forms.Control.set_Text(String value)
   在 DevExpress.XtraEditors.LabelControl.set_Text(String value)
   在 UserComponents.FlashDownLoadComp.DownLoadTaskItem.SetItemStatus() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\DownLoadTaskItem.cs:行号 107
   在 UserComponents.FlashDownLoadComp.TaskItem.set_ItemStatus(TaskStatus value) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\FlashDownLoadComp\TaskItem.cs:行号 162
   在 FlashDownLoad.DownLoadForm.Task_TaskFinish(Object sender, TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\FlashDownLoad\DownLoadForm.cs:行号 720
   在 UserComponents.DownLoadService.DownLoadTask.OnTaskFinish(TaskFinishEventArgs e) 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\DownLoadTask.cs:行号 616
   在 UserComponents.DownLoadService.HttpDownLoadTask.AsyncStart() 位置 E:\pzh\CSharpSource\P2SP\UserComponents\DownLoadService\HttpDownLoadTask.cs:行号 118                                   
【错误详情】
